repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: end-of-file-fixer
      - id: check-case-conflict
      - id: check-vcs-permalinks
      - id: trailing-whitespace
      - id: check-byte-order-marker
      - id: check-symlinks
      - id: check-merge-conflict
      - id: mixed-line-ending
      # - id: no-commit-to-branch
      #   args: [--branch, staging, --pattern, ci.*, --branch, main]
      - id: check-added-large-files
        args: ['--maxkb=51200']
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-toml
  # - repo: https://github.com/markdownlint/markdownlint
  #   rev: v0.13.0
  #   hooks:
  #     - id: markdownlint
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        exclude: ^package.*\.json$
  - repo: https://github.com/crate-ci/typos
    rev: v1.29.7
    hooks:
      - id: typos
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
      - id: gitlint
  # - repo: https://github.com/commitizen-tools/commitizen
  #   rev: v4.2.2
  #   hooks:
  #     # - id: commitizen
  #     - id: commitizen-branch
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.23.3
    hooks:
      - id: gitleaks
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.0.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [--verbose] # optional: list of Conventional Commits types to allow e.g. [feat, fix, ci, chore, test]
  - repo: https://github.com/gitguardian/ggshield
    rev: v1.36.0
    hooks:
      - id: ggshield
        language_version: python3
        stages: [pre-commit]
      - id: ggshield-push
        language_version: python3
        stages: [pre-push]
  # - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
  #   rev: v9.21.0
  #   hooks:
  #     - id: commitlint
  #       stages: [commit-msg]
  #       additional_dependencies: ['@commitlint/cli', '@commitlint/config-conventional']
